<?php
require_once '../../includes/auth.php';
requireLogin();
requirePermission('view');
require_once '../../includes/db.php';
?>
<?php require_once '../../includes/header.php'; ?>
<?php require_once '../../includes/sidebar.php'; ?>

<h4 class="fw-bold mb-4"><i class="bi bi-file-earmark-text me-2 text-primary"></i>Reports</h4>

<div class="row g-3">
    <div class="col-md-4">
        <div class="card border-0 shadow-sm h-100">
            <div class="card-body text-center p-4">
                <i class="bi bi-file-earmark-ruled text-primary" style="font-size:2.5rem;"></i>
                <h5 class="mt-3 fw-bold">RIS</h5>
                <p class="text-muted small">Requisition and Issue Slip</p>
                <a href="generate.php?type=RIS" class="btn btn-primary w-100">Generate RIS</a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card border-0 shadow-sm h-100">
            <div class="card-body text-center p-4">
                <i class="bi bi-clipboard-check text-success" style="font-size:2.5rem;"></i>
                <h5 class="mt-3 fw-bold">ICS</h5>
                <p class="text-muted small">Inventory Custodian Slip</p>
                <a href="generate.php?type=ICS" class="btn btn-success w-100">Generate ICS</a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card border-0 shadow-sm h-100">
            <div class="card-body text-center p-4">
                <i class="bi bi-person-check text-warning" style="font-size:2.5rem;"></i>
                <h5 class="mt-3 fw-bold">PAR</h5>
                <p class="text-muted small">Property Acknowledgement Receipt</p>
                <a href="generate.php?type=PAR" class="btn btn-warning w-100">Generate PAR</a>
            </div>
        </div>
    </div>
</div>

<div class="card border-0 shadow-sm mt-4">
    <div class="card-header bg-white fw-semibold">
        <i class="bi bi-clock-history me-2 text-primary"></i>Recent Reports Generated
    </div>
    <div class="card-body p-0">
        <?php
        $recent = $conn->query("SELECT r.*, u.full_name FROM reports_log r LEFT JOIN users u ON r.generated_by = u.user_id ORDER BY r.generated_at DESC LIMIT 10");
        ?>
        <table class="table table-hover mb-0">
            <thead>
                <tr>
                    <th>Report Type</th>
                    <th>Period</th>
                    <th>Generated By</th>
                    <th>Date Generated</th>
                </tr>
            </thead>
            <tbody>
                <?php if ($recent->num_rows > 0): ?>
                    <?php while($row = $recent->fetch_assoc()): ?>
                    <tr>
                        <td>
                            <?php
                            $badge_class = 'bg-primary';
                            if ($row['report_type'] === 'ICS') $badge_class = 'bg-success';
                            if ($row['report_type'] === 'PAR') $badge_class = 'bg-warning text-dark';
                            ?>
                            <span class="badge <?php echo $badge_class; ?>"><?php echo $row['report_type']; ?></span>
                        </td>
                        <td><?php echo $row['period_type'] . ($row['period_value'] ? ' - ' . $row['period_value'] : ''); ?></td>
                        <td><?php echo htmlspecialchars($row['full_name'] ?? 'N/A'); ?></td>
                        <td><?php echo date('M d, Y h:i A', strtotime($row['generated_at'])); ?></td>
                    </tr>
                    <?php endwhile; ?>
                <?php else: ?>
                    <tr><td colspan="4" class="text-center text-muted py-4">No reports generated yet.</td></tr>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>

<?php require_once '../../includes/footer.php'; ?>
