<?php
require_once '../../includes/auth.php';
requireLogin();
requirePermission('view');
require_once '../../includes/db.php';
?>
<?php require_once '../../includes/header.php'; ?>
<?php require_once '../../includes/sidebar.php'; ?>

<?php
$report_filter = $_GET['type'] ?? '';
$report_filter = in_array($report_filter, ['RIS', 'ICS', 'RIPE', 'PAR'], true) ? $report_filter : '';
$report_sort = $_GET['sort'] ?? 'date';
$report_direction = strtoupper($_GET['direction'] ?? 'DESC');
$report_sort_columns = ['date' => 'r.generated_at', 'type' => 'r.report_type', 'period' => 'r.period_type', 'user' => 'u.full_name'];
$report_sort = array_key_exists($report_sort, $report_sort_columns) ? $report_sort : 'date';
$report_direction = in_array($report_direction, ['ASC', 'DESC'], true) ? $report_direction : 'DESC';
?>

<h4 class="fw-bold mb-4"><i class="bi bi-file-earmark-text me-2 text-primary"></i>Reports</h4>

<div class="row g-3">
    <div class="col-md-4">
        <div class="card border-0 shadow-sm h-100">
            <div class="card-body text-center p-4">
                <i class="bi bi-file-earmark-ruled text-primary" style="font-size:2.5rem;"></i>
                <h5 class="mt-3 fw-bold">RIS</h5>
                <p class="text-muted small">Requisition and Issue Slip</p>
                <a href="generate.php?type=RIS" class="btn btn-primary w-100">Generate RIS</a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card border-0 shadow-sm h-100">
            <div class="card-body text-center p-4">
                <i class="bi bi-file-earmark-person text-danger" style="font-size:2.5rem;"></i>
                <h5 class="mt-3 fw-bold">PAR</h5>
                <p class="text-muted small">Property Acknowledgment Receipt</p>
                <a href="generate.php?type=PAR" class="btn btn-danger w-100">Generate PAR</a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card border-0 shadow-sm h-100">
            <div class="card-body text-center p-4">
                <i class="bi bi-clipboard-check text-success" style="font-size:2.5rem;"></i>
                <h5 class="mt-3 fw-bold">ICS</h5>
                <p class="text-muted small">Inventory Custodian Slip</p>
                <a href="generate.php?type=ICS" class="btn btn-success w-100">Generate ICS</a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card border-0 shadow-sm h-100">
            <div class="card-body text-center p-4">
                <i class="bi bi-clipboard-data text-warning" style="font-size:2.5rem;"></i>
                <h5 class="mt-3 fw-bold">RIPE</h5>
                <p class="text-muted small">Report on Inventory of Property and Equipment</p>
                <a href="generate.php?type=RIPE" class="btn btn-warning w-100">Generate RIPE</a>
            </div>
        </div>
    </div>
</div>

<div class="card border-0 shadow-sm mt-4">
    <div class="card-header bg-white fw-semibold">
        <i class="bi bi-clock-history me-2 text-primary"></i>Recent Reports Generated
    </div>
    <div class="card-body p-0">
        <?php
        $report_where = $report_filter ? "WHERE r.report_type = '" . $conn->real_escape_string($report_filter) . "'" : '';
        $recent = $conn->query("SELECT r.*, u.full_name FROM reports_log r LEFT JOIN users u ON r.generated_by = u.user_id $report_where ORDER BY {$report_sort_columns[$report_sort]} $report_direction LIMIT 50");
        ?>
        <form method="GET" class="row g-2 p-3 align-items-end filter-toolbar">
            <div class="col-md-4"><label class="form-label">Report type</label><select name="type" class="form-select"><option value="">All reports</option><option value="RIS" <?php echo $report_filter === 'RIS' ? 'selected' : ''; ?>>RIS</option><option value="ICS" <?php echo $report_filter === 'ICS' ? 'selected' : ''; ?>>ICS</option><option value="RIPE" <?php echo $report_filter === 'RIPE' ? 'selected' : ''; ?>>RIPE</option><option value="PAR" <?php echo $report_filter === 'PAR' ? 'selected' : ''; ?>>PAR</option></select></div>
            <div class="col-md-3"><label class="form-label">Sort by</label><select name="sort" class="form-select"><option value="date" <?php echo $report_sort === 'date' ? 'selected' : ''; ?>>Date</option><option value="type" <?php echo $report_sort === 'type' ? 'selected' : ''; ?>>Type</option><option value="period" <?php echo $report_sort === 'period' ? 'selected' : ''; ?>>Period</option><option value="user" <?php echo $report_sort === 'user' ? 'selected' : ''; ?>>Generated by</option></select></div>
            <div class="col-md-3"><label class="form-label">Direction</label><select name="direction" class="form-select"><option value="DESC" <?php echo $report_direction === 'DESC' ? 'selected' : ''; ?>>Descending</option><option value="ASC" <?php echo $report_direction === 'ASC' ? 'selected' : ''; ?>>Ascending</option></select></div>
            <div class="col-md-2"><button type="submit" class="btn btn-primary w-100">Apply</button></div>
        </form>
        <table class="table table-hover mb-0">
            <thead>
                <tr>
                    <th>Report Type</th>
                    <th>Period</th>
                    <th>Generated By</th>
                    <th>Date Generated</th>
                </tr>
            </thead>
            <tbody>
                <?php if ($recent->num_rows > 0): ?>
                    <?php while($row = $recent->fetch_assoc()): ?>
                    <tr>
                        <td>
                            <?php
                            $badge_class = 'bg-primary';
                            if ($row['report_type'] === 'ICS') $badge_class = 'bg-success';
                            if ($row['report_type'] === 'RIPE') $badge_class = 'bg-warning text-dark';
                            if ($row['report_type'] === 'PAR') $badge_class = 'bg-danger';
                            ?>
                            <span class="badge <?php echo $badge_class; ?>"><?php echo $row['report_type']; ?></span>
                        </td>
                        <td><?php echo $row['period_type'] . ($row['period_value'] ? ' - ' . $row['period_value'] : ''); ?></td>
                        <td><?php echo htmlspecialchars($row['full_name'] ?? 'N/A'); ?></td>
                        <td><?php echo date('M d, Y h:i A', strtotime($row['generated_at'])); ?></td>
                    </tr>
                    <?php endwhile; ?>
                <?php else: ?>
                    <tr><td colspan="4" class="text-center text-muted py-4">No reports generated yet.</td></tr>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>

<?php require_once '../../includes/footer.php'; ?>
